name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v3
      - users: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm ci

      - run: pnpm test
